### ISSUE TITLE
Troubles with GEMOC examples...

### ISSUE THREAD

**Issue by rleroux02** [gemoc/gemoc-studio#29]
Hi Gemoc Team,

I have installed the following examples from last version of Gemoc studio : 2.2.1 SNAPSHOT  2016-11-09 21:44 and I get errors after installing them:

- GEMOC operator for TFSM and SigPML Languages (Coordination)
- GEMOC SigPML Language (Concurrent)
- GEMOC TFSM Language (concurrent)

In hope to correct these difficulties, I have executed the commands « Clean All » and « Generate All » on files:

- _Main.melange_ of  org.gemoc.sample.sigpml package
- _Main.melange_ of  org.gemoc.sample.tfsm.concurrent

As I am a newcomer to Gemoc, I probably missed something but it difficult to learn how it works without functional examples. 

Your help is therefore welcome!

Renan 

—— 
The errors are:

```
Description	Resource	Path	Location	Type
org.gemoc.sample.tfsm.concurrent.k3dsa.aspect.EvaluateGuardAspect cannot be resolved to a type.	Main.melange	/org.gemoc.sample.tfsm.concurrent/src/org/gemoc/sample/tfsm/concurrent	line: 23 /org.gemoc.sample.tfsm.concurrent/src/org/gemoc/sample/tfsm/concurrent/Main.melange	Melange Problem
org.gemoc.sample.tfsm.concurrent.k3dsa.aspect.EventGuardAspect cannot be resolved to a type.	Main.melange	/org.gemoc.sample.tfsm.concurrent/src/org/gemoc/sample/tfsm/concurrent	line: 19 /org.gemoc.sample.tfsm.concurrent/src/org/gemoc/sample/tfsm/concurrent/Main.melange	Melange Problem
org.gemoc.sample.tfsm.concurrent.k3dsa.aspect.FSMClockAspect cannot be resolved to a type.	Main.melange	/org.gemoc.sample.tfsm.concurrent/src/org/gemoc/sample/tfsm/concurrent	line: 21 /org.gemoc.sample.tfsm.concurrent/src/org/gemoc/sample/tfsm/concurrent/Main.melange	Melange Problem
org.gemoc.sample.tfsm.concurrent.k3dsa.aspect.FSMEventAspect cannot be resolved to a type.	Main.melange	/org.gemoc.sample.tfsm.concurrent/src/org/gemoc/sample/tfsm/concurrent	line: 20 /org.gemoc.sample.tfsm.concurrent/src/org/gemoc/sample/tfsm/concurrent/Main.melange	Melange Problem
org.gemoc.sample.tfsm.concurrent.k3dsa.aspect.GuardAspect cannot be resolved to a type.	Main.melange	/org.gemoc.sample.tfsm.concurrent/src/org/gemoc/sample/tfsm/concurrent	line: 17 /org.gemoc.sample.tfsm.concurrent/src/org/gemoc/sample/tfsm/concurrent/Main.melange	Melange Problem
org.gemoc.sample.tfsm.concurrent.k3dsa.aspect.NamedElementAspect cannot be resolved to a type.	Main.melange	/org.gemoc.sample.tfsm.concurrent/src/org/gemoc/sample/tfsm/concurrent	line: 16 /org.gemoc.sample.tfsm.concurrent/src/org/gemoc/sample/tfsm/concurrent/Main.melange	Melange Problem
org.gemoc.sample.tfsm.concurrent.k3dsa.aspect.StateAspect cannot be resolved to a type.	Main.melange	/org.gemoc.sample.tfsm.concurrent/src/org/gemoc/sample/tfsm/concurrent	line: 14 /org.gemoc.sample.tfsm.concurrent/src/org/gemoc/sample/tfsm/concurrent/Main.melange	Melange Problem
org.gemoc.sample.tfsm.concurrent.k3dsa.aspect.TemporalGuardAspect cannot be resolved to a type.	Main.melange	/org.gemoc.sample.tfsm.concurrent/src/org/gemoc/sample/tfsm/concurrent	line: 18 /org.gemoc.sample.tfsm.concurrent/src/org/gemoc/sample/tfsm/concurrent/Main.melange	Melange Problem
org.gemoc.sample.tfsm.concurrent.k3dsa.aspect.TFSMAspect cannot be resolved to a type.	Main.melange	/org.gemoc.sample.tfsm.concurrent/src/org/gemoc/sample/tfsm/concurrent	line: 13 /org.gemoc.sample.tfsm.concurrent/src/org/gemoc/sample/tfsm/concurrent/Main.melange	Melange Problem
org.gemoc.sample.tfsm.concurrent.k3dsa.aspect.TimedSystemAspect cannot be resolved to a type.	Main.melange	/org.gemoc.sample.tfsm.concurrent/src/org/gemoc/sample/tfsm/concurrent	line: 22 /org.gemoc.sample.tfsm.concurrent/src/org/gemoc/sample/tfsm/concurrent/Main.melange	Melange Problem
org.gemoc.sample.tfsm.concurrent.k3dsa.aspect.TransitionAspect cannot be resolved to a type.	Main.melange	/org.gemoc.sample.tfsm.concurrent/src/org/gemoc/sample/tfsm/concurrent	line: 15 /org.gemoc.sample.tfsm.concurrent/src/org/gemoc/sample/tfsm/concurrent/Main.melange	Melange Problem
Package 'org.gemoc.sample.tfsm.concurrent.xtfsm.aspects' does not exist in this plug-in	MANIFEST.MF	/org.gemoc.sample.tfsm.concurrent.xtfsm/META-INF	line 15	Plug-in Problem
Unresolved '' 'Agent'	SigPML.ecl	/org.gemoc.sample.sigpml.moc.dse/MoCApplication	line: 87 /org.gemoc.sample.sigpml.moc.dse/MoCApplication/SigPML.ecl	Xtext Check (fast)
Unresolved '' 'Agent'	SigPML.ecl	/org.gemoc.sample.sigpml.moc.dse/MoCApplication	line: 9 /org.gemoc.sample.sigpml.moc.dse/MoCApplication/SigPML.ecl	Xtext Check (fast)
Unresolved '' 'HWComputationalResource'	SigPML.ecl	/org.gemoc.sample.sigpml.moc.dse/MoCApplication	line: 27 /org.gemoc.sample.sigpml.moc.dse/MoCApplication/SigPML.ecl	Xtext Check (fast)
Unresolved '' 'HWComputationalResource'	SigPML.ecl	/org.gemoc.sample.sigpml.moc.dse/MoCApplication	line: 96 /org.gemoc.sample.sigpml.moc.dse/MoCApplication/SigPML.ecl	Xtext Check (fast)
Unresolved '' 'HWStorageResource'	SigPML.ecl	/org.gemoc.sample.sigpml.moc.dse/MoCApplication	line: 117 /org.gemoc.sample.sigpml.moc.dse/MoCApplication/SigPML.ecl	Xtext Check (fast)
Unresolved '' 'HWStorageResource'	SigPML.ecl	/org.gemoc.sample.sigpml.moc.dse/MoCApplication	line: 31 /org.gemoc.sample.sigpml.moc.dse/MoCApplication/SigPML.ecl	Xtext Check (fast)
Unresolved '' 'InputPort'	SigPML.ecl	/org.gemoc.sample.sigpml.moc.dse/MoCApplication	line: 14 /org.gemoc.sample.sigpml.moc.dse/MoCApplication/SigPML.ecl	Xtext Check (fast)
Unresolved '' 'InputPort'	SigPML.ecl	/org.gemoc.sample.sigpml.moc.dse/MoCApplication	line: 59 /org.gemoc.sample.sigpml.moc.dse/MoCApplication/SigPML.ecl	Xtext Check (fast)
Unresolved '' 'OutputPort'	SigPML.ecl	/org.gemoc.sample.sigpml.moc.dse/MoCApplication	line: 18 /org.gemoc.sample.sigpml.moc.dse/MoCApplication/SigPML.ecl	Xtext Check (fast)
Unresolved '' 'OutputPort'	SigPML.ecl	/org.gemoc.sample.sigpml.moc.dse/MoCApplication	line: 74 /org.gemoc.sample.sigpml.moc.dse/MoCApplication/SigPML.ecl	Xtext Check (fast)
Unresolved '' 'Place'	SigPML.ecl	/org.gemoc.sample.sigpml.moc.dse/MoCApplication	line: 21 /org.gemoc.sample.sigpml.moc.dse/MoCApplication/SigPML.ecl	Xtext Check (fast)
Unresolved '' 'Place'	SigPML.ecl	/org.gemoc.sample.sigpml.moc.dse/MoCApplication	line: 35 /org.gemoc.sample.sigpml.moc.dse/MoCApplication/SigPML.ecl	Xtext Check (fast)
Unresolved '' 'sigpml'	SigPML.ecl	/org.gemoc.sample.sigpml.moc.dse/MoCApplication	line: 7 /org.gemoc.sample.sigpml.moc.dse/MoCApplication/SigPML.ecl	Xtext Check (fast)
Unresolved import 'http://org.gemoc.sample.sigpml.xsigpml/sigpml/' : org.gemoc.sample.sigpml.xsigpml	SigPML.ecl	/org.gemoc.sample.sigpml.moc.dse/MoCApplication	line: 1 /org.gemoc.sample.sigpml.moc.dse/MoCApplication/SigPML.ecl	Xtext Check (fast)
Unresolved Type 'Place'	SigPML.ecl	/org.gemoc.sample.sigpml.moc.dse/MoCApplication	line: 71 /org.gemoc.sample.sigpml.moc.dse/MoCApplication/SigPML.ecl	Xtext Check (fast)
Unresolved Type 'Place'	SigPML.ecl	/org.gemoc.sample.sigpml.moc.dse/MoCApplication	line: 84 /org.gemoc.sample.sigpml.moc.dse/MoCApplication/SigPML.ecl	Xtext Check (fast)
```

**Comment by jdeantoni** [comment]
Hi,

TFSM concurrent works for me with the latest version available on gemoc.org: Version: 2.2.0-SNAPSHOT
Build id: 2016-10-07 00:43 with minor changes

in a fresh workspace:

new -> example -> TFSM concurrent, then right click and generate all on the melange file (in the *.concurrent project)

Then on the *.xtfsm project, right click-> configure -> Enable autoregister ecore file

Then (not sure it is required but never a bad idea :) ) help -> install new software -> choose Timesquare ECL update site -> install all (it will actually update it)

Then you may be able to simulate in the modeling workbench.
Note that there is a minor problem with some part of the animation (no color changes) but you will still see the changes in the model variables.

(the animator error is 
`Exception in Addon (org.gemoc.executionframework.extensions.sirius.services.AbstractGemocAnimatorServices$GemocModelAnimator@3e069038), java.lang.NullPointerException
	at org.eclipse.emf.ecore.util.EcoreUtil.getURI(EcoreUtil.java:3048) `
)

**Comment by rleroux02** [comment]
Bonjour Julien,

Super pour les info.
Je regarde cela de suite.
Merci pour ton aide.
Renan


De : julien deantoni [mailto:notifications@github.com]
Envoyé : mercredi 23 novembre 2016 14:18
À : gemoc/gemoc-studio
Cc : LEROUX-BEAUDOUT Renan; Author
Objet : Re: [gemoc/gemoc-studio] Troubles with GEMOC examples... (#29)


Hi,

TFSM concurrent works for me with the latest version available on gemoc.org: Version: 2.2.0-SNAPSHOT
Build id: 2016-10-07 00:43 with minor changes

in a fresh workspace:

new -> example -> TFSM concurrent, then right click and generate all on the melange file (in the *.concurrent project)

Then on the *.xtfsm project, right click-> configure -> Enable autoregister ecore file

Then (not sure it is required but never a bad idea :) ) help -> install new software -> choose Timesquare ECL update site -> install all (it will actually update it)

Then you may be able to simulate in the modeling workbench.
Note that there is a minor problem with some part of the animation (no color changes) but you will still see the changes in the model variables.

(the animator error is
Exception in Addon (org.gemoc.executionframework.extensions.sirius.services.AbstractGemocAnimatorServices$GemocModelAnimator@3e069038<mailto:org.gemoc.executionframework.extensions.sirius.services.AbstractGemocAnimatorServices$GemocModelAnimator@3e069038>), java.lang.NullPointerException at org.eclipse.emf.ecore.util.EcoreUtil.getURI(EcoreUtil.java:3048)
)
