### ISSUE TITLE
errors when creating DSA project

### ISSUE THREAD

**Issue by zzhang03** [gemoc/gemoc-studio#36]
Hi Gemoc team,
Sorry to bother you again. I began to implement a toy model by myself now. I added ED and EF to my meta-model by simply adding attributes and an operation to the classes, regenerated code, edit and editor then generate DSA project. However xtend file compilation gave me a lot of errors and I couldn't figure out why. Since I'm new to this area I'm not quite sure if I extended my AS with ED and EF correctly. Is there anything special about that? Or do you have anything in mind about what caused the problem? Thank you.

Error messages:

It gave null exception on the first line of the xtend file which specify package. It also couldn't resolve all the classNames and aspectized classes

**Comment by zzhang03** [comment]
error log:

org.eclipse.xtext.builder.BuilderParticipant  - Error during compilation of 'platform:/resource/com.samsung.xmaps.sample.family.k3dsa/src/family/aspects/familyAspects.xtend'

java.lang.NullPointerException
	at fr.inria.diverse.k3.al.annotationprocessor.AspectProcessor.doGenerateCode(AspectProcessor.java:142)
	at org.eclipse.xtend.core.compiler.XtendGenerator.callMacroProcessors(XtendGenerator.java:158)
	at org.eclipse.xtend.core.compiler.XtendGenerator.doGenerate(XtendGenerator.java:105)
	at org.eclipse.xtend.core.compiler.XtendGenerator.doGenerate(XtendGenerator.java:120)
	at org.eclipse.xtext.generator.GeneratorDelegate.doGenerate(GeneratorDelegate.java:43)
	at org.eclipse.xtext.builder.ParallelBuilderParticipant.handleChangedContents(ParallelBuilderParticipant.java:183)
	at org.eclipse.xtext.builder.ParallelBuilderParticipant.handleChangedContents(ParallelBuilderParticipant.java:172)
	at org.eclipse.xtext.builder.ParallelBuilderParticipant.doGenerate(ParallelBuilderParticipant.java:343)
	at org.eclipse.xtext.builder.ParallelBuilderParticipant$1.run(ParallelBuilderParticipant.java:308)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by dvojtise** [comment]
Hi 
Depending on the steps you followed and from which files you started the wizards (from the menu, from a right click on a file/project, or from completion in the melange file), the wizard may not automatically fill all the fields.
The generate DSA may have generated the .xtend files with incorrect  packages prefix for the import statements.

Usually, you can manually fix the import statements in the .xtend files so they correctly points to the java files in the .model project.

**Comment by zzhang03** [comment]
I followed the steps of the markedgraph example. I compared my case with the example, the generated xtend file looks the same. But when I saw you mentioned the basePackage I checked this field and found that I had a predefined basePackage while the example didn't. So I cleared this field and regenerated everything then the bugs are gone. Thank you for your help. :)
