### ISSUE TITLE
Error when installing xMOF with components discovery: "java.lang.RuntimeException: Operation details"

### ISSUE THREAD

**Issue by ebousse** [gemoc/gemoc-studio#39]
Using the latest studio (12-Apr-2017 17:45), when using the components discovery to install xMOF, I have an error saying "Problems occured" and the following exception in the log:
~~~
java.lang.RuntimeException: Operation details
	at org.eclipse.amalgam.discovery.ui.common.internal.PrepareInstallProfileJob.resolve(PrepareInstallProfileJob.java:143)
	at org.eclipse.amalgam.discovery.ui.common.internal.PrepareInstallProfileJob.run(PrepareInstallProfileJob.java:104)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
~~~

Screenshot:
![capture du 2017-04-13 15-51-51](https://cloud.githubusercontent.com/assets/5868014/25007734/c284ebbc-2061-11e7-8b85-48a606970a1e.png)

I was not sure to put the issue on the moliz.gemoc repo or here, but since the error happens before having installed xMOF, I thought here was better :)

**Comment by dvojtise** [comment]
It was actually not looking to neon update site to install additional components (graphiti for example)
I've added it to the search and now it seems to install correctly.
However I've opened bug #40 in order to have an action to improve the error message in such situation.

**Comment by deaddysBoy** [comment]
hi,
i am still getting this error while on the latest snapshot version.

Version: 2.3.0-SNAPSHOT
Build id: 2017-07-17 10:49

Is there another way to install the component?

**Comment by dvojtise** [comment]
Yes, you can use the update site directly. In that case, you'll be able to see what's wrong for a given combination of GEMOC version / Xmof version.

ie. use the following update site : http://moliz.github.io/moliz.gemoc/updatesite/nightly/
Then install the features from it. The error message should be more verbose.

GEMOC studio code had undergone some major refactoring last months in order to be able to push it into eclipse foundation. (need to change all the plugin and java namespaces using org.eclipse.gemoc for example) We are also refactoring all the build system in order to use Eclipse CI, web sites etc, (see current progress [Gemoc dev resource @ eclipse](https://projects.eclipse.org/projects/modeling.gemoc/developer))
so I won't be surprised that xmof team hadn't the time to migrate xmof to the latest versions of gemoc.
