### ISSUE TITLE
Error when installing  with components discovery: "java.lang.RuntimeException: Operation details"

### ISSUE THREAD

**Issue by dvojtise** [gemoc/gemoc-studio#40]
When some componetn doesn't install correctly due to missing pre-installed feature, the message doesn't contains any useful information.
```
java.lang.RuntimeException: Operation details
	at org.eclipse.amalgam.discovery.ui.common.internal.PrepareInstallProfileJob.resolve(PrepareInstallProfileJob.java:143)
	at org.eclipse.amalgam.discovery.ui.common.internal.PrepareInstallProfileJob.run(PrepareInstallProfileJob.java:104)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
```

that was the case for xmof (see bug #39 ) and is currently the case when installing uml designer.

we need to find a way to capture the resolve problem and report it to the user

**Comment by dvojtise** [comment]
This issue was moved to eclipse/gemoc-studio#52
