### ISSUE TITLE
Problem about GEMOC Debug Configuration

### ISSUE THREAD

**Issue by JoyeGCL** [gemoc/gemoc-studio#61]
Hi GEMOC team,
    Can anyone help me?
    In GEMOC language workbench, I have created a new DSL ( 1. abstract syntax-ecore model,  2.concrete syntax using Sirius,  3.Operational semantics via k3 project ,  4.create GEMOC sequential xDSML project, melange have generate all). 
    Then in GEMOC modeling workbench, I create a project for model  , but when I Debug , the problem occurred tells me that Could not find method InitialModel with correct parameters.

Error occured when starting execution engine: Could not find method InitializeModel with correct parameters. (see inner exception).
java.lang.RuntimeException: Could not find method InitializeModel with correct parameters.
	at org.gemoc.execution.sequential.javaengine.PlainK3ExecutionEngine.prepareInitializeModel(PlainK3ExecutionEngine.java:196)
	at org.gemoc.executionframework.engine.core.AbstractSequentialExecutionEngine.performInitialize(AbstractSequentialExecutionEngine.java:75)
	at org.gemoc.executionframework.engine.core.AbstractExecutionEngine.initialize(AbstractExecutionEngine.java:86)
	at org.gemoc.execution.sequential.javaengine.ui.launcher.Launcher.createExecutionEngine(Launcher.java:66)
	at org.gemoc.executionframework.engine.ui.launcher.AbstractSequentialGemocLauncher.launch(AbstractSequentialGemocLauncher.java:104)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

   Look forward to your reply.

**Comment by dvojtise** [comment]
Hi
you seems to use the "old" org.gemoc version instead of the eclipse version (there were some issue with the initialization method and I don't remember exactly the workaround/way to declare it in order to make it work)

could you try with this version of the studio : http://download.eclipse.org/gemoc/packages/milestones/3.0.0rc1/?d (click on show directory content to see the zip files) ?

i knwon, ee need to update the download page to point to download.eclipse.org page now ...

**Comment by JoyeGCL** [comment]
Hi Dvojtise，
     Thank you for your prompt reply. 
      I  did use GEMOC 2.3.0 before. In this morning, I download the Eclipse GemocStudio 3.0.0  Build id: 2018-01-22 04:38 from [https://projects.eclipse.org/projects/modeling.gemoc/downloads](https://projects.eclipse.org/projects/modeling.gemoc/downloads). 
     Firstly,in language workbench
     1. I create a new Ecore Modeling Project named org.snow.fsmode.model, generate all from genmodel 
     2. I create a Viewpoint Specification Project 
     3.I create a Gemoc Sequential xDSML Project
     4.Right click on melange file, I create DSA Project for language and writed xtend file
     Secondly, in modeling workbench
     1. I create a Modeling Project and create a simple model
     2.I want to dubug the model comforms to the DSL. But it is still wrong.
     
    **There are two errors.**

Error1: An internal error occurred during: "Launching Debug1"
java.lang.NoClassDefFoundError: fr/inria/diverse/melange/resource/MelangeResourceImpl
	at org.eclipse.gemoc.executionframework.extensions.sirius.modelloader.DefaultModelLoader.openNewSiriusSession(DefaultModelLoader.java:237)
	at org.eclipse.gemoc.executionframework.extensions.sirius.modelloader.DefaultModelLoader.loadModel(DefaultModelLoader.java:167)
	at org.eclipse.gemoc.executionframework.extensions.sirius.modelloader.DefaultModelLoader.loadModelForAnimation(DefaultModelLoader.java:128)
	at org.eclipse.gemoc.executionframework.engine.commons.ModelExecutionContext.initializeResourceModel(ModelExecutionContext.java:71)
	at org.eclipse.gemoc.execution.sequential.javaengine.ui.launcher.Launcher.createExecutionEngine(Launcher.java:64)
	at org.eclipse.gemoc.executionframework.engine.ui.launcher.AbstractSequentialGemocLauncher.launch(AbstractSequentialGemocLauncher.java:106)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.lang.ClassNotFoundException: An error occurred while automatically activating bundle fr.inria.diverse.melange.resource (23).
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:112)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:529)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:328)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:368)
	at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:36)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:442)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 11 more
Caused by: org.osgi.framework.BundleException: Exception in fr.inria.diverse.melange.resource.Activator.start() of bundle fr.inria.diverse.melange.resource.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:800)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:729)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:933)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:309)
	at org.eclipse.osgi.container.Module.doStart(Module.java:581)
	at org.eclipse.osgi.container.Module.start(Module.java:449)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:468)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:103)
	... 20 more
Caused by: org.eclipse.core.runtime.CoreException: Plug-in org.snow.xfsmode was unable to load class org.snow.xfsmode.xfsmode.adapters.xfsmodemt.XFSMODEAdapter.
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:194)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:176)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
	at fr.inria.diverse.melange.resource.Activator$2$1$1.accept(Activator.java:83)
	at fr.inria.diverse.melange.resource.Activator$2$1$1.accept(Activator.java:1)
	at java.lang.Iterable.forEach(Unknown Source)
	at fr.inria.diverse.melange.resource.Activator$2$1.apply(Activator.java:92)
	at fr.inria.diverse.melange.resource.Activator$2$1.apply(Activator.java:1)
	at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
	at fr.inria.diverse.melange.resource.Activator$2.accept(Activator.java:95)
	at fr.inria.diverse.melange.resource.Activator$2.accept(Activator.java:1)
	at java.lang.Iterable.forEach(Unknown Source)
	at fr.inria.diverse.melange.resource.Activator.start(Activator.java:101)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:779)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:772)
	... 27 more
Caused by: java.lang.ClassNotFoundException: org.snow.xfsmode.xfsmode.adapters.xfsmodemt.XFSMODEAdapter cannot be found by org.snow.xfsmode_1.0.0
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:484)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:564)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:174)
	... 44 more



Error2.An error occurred while automatically activating bundle fr.inria.diverse.melange.resource 
org.osgi.framework.BundleException: Exception in fr.inria.diverse.melange.resource.Activator.start() of bundle fr.inria.diverse.melange.resource.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:800)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:729)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:933)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:309)
	at org.eclipse.osgi.container.Module.doStart(Module.java:581)
	at org.eclipse.osgi.container.Module.start(Module.java:449)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:468)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:103)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:529)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:328)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:368)
	at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:36)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:442)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.gemoc.executionframework.extensions.sirius.modelloader.DefaultModelLoader.openNewSiriusSession(DefaultModelLoader.java:237)
	at org.eclipse.gemoc.executionframework.extensions.sirius.modelloader.DefaultModelLoader.loadModel(DefaultModelLoader.java:167)
	at org.eclipse.gemoc.executionframework.extensions.sirius.modelloader.DefaultModelLoader.loadModelForAnimation(DefaultModelLoader.java:128)
	at org.eclipse.gemoc.executionframework.engine.commons.ModelExecutionContext.initializeResourceModel(ModelExecutionContext.java:71)
	at org.eclipse.gemoc.execution.sequential.javaengine.ui.launcher.Launcher.createExecutionEngine(Launcher.java:64)
	at org.eclipse.gemoc.executionframework.engine.ui.launcher.AbstractSequentialGemocLauncher.launch(AbstractSequentialGemocLauncher.java:106)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: org.eclipse.core.runtime.CoreException: Plug-in org.snow.xfsmode was unable to load class org.snow.xfsmode.xfsmode.adapters.xfsmodemt.XFSMODEAdapter.
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:194)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:176)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
	at fr.inria.diverse.melange.resource.Activator$2$1$1.accept(Activator.java:83)
	at fr.inria.diverse.melange.resource.Activator$2$1$1.accept(Activator.java:1)
	at java.lang.Iterable.forEach(Unknown Source)
	at fr.inria.diverse.melange.resource.Activator$2$1.apply(Activator.java:92)
	at fr.inria.diverse.melange.resource.Activator$2$1.apply(Activator.java:1)
	at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
	at fr.inria.diverse.melange.resource.Activator$2.accept(Activator.java:95)
	at fr.inria.diverse.melange.resource.Activator$2.accept(Activator.java:1)
	at java.lang.Iterable.forEach(Unknown Source)
	at fr.inria.diverse.melange.resource.Activator.start(Activator.java:101)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:779)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:772)
	... 27 more
Caused by: java.lang.ClassNotFoundException: org.snow.xfsmode.xfsmode.adapters.xfsmodemt.XFSMODEAdapter cannot be found by org.snow.xfsmode_1.0.0
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:484)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:564)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:174)
	... 44 more
Root exception:
org.eclipse.core.runtime.CoreException: Plug-in org.snow.xfsmode was unable to load class org.snow.xfsmode.xfsmode.adapters.xfsmodemt.XFSMODEAdapter.
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:194)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:176)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
	at fr.inria.diverse.melange.resource.Activator$2$1$1.accept(Activator.java:83)
	at fr.inria.diverse.melange.resource.Activator$2$1$1.accept(Activator.java:1)
	at java.lang.Iterable.forEach(Unknown Source)
	at fr.inria.diverse.melange.resource.Activator$2$1.apply(Activator.java:92)
	at fr.inria.diverse.melange.resource.Activator$2$1.apply(Activator.java:1)
	at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
	at fr.inria.diverse.melange.resource.Activator$2.accept(Activator.java:95)
	at fr.inria.diverse.melange.resource.Activator$2.accept(Activator.java:1)
	at java.lang.Iterable.forEach(Unknown Source)
	at fr.inria.diverse.melange.resource.Activator.start(Activator.java:101)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:779)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:772)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:729)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:933)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:309)
	at org.eclipse.osgi.container.Module.doStart(Module.java:581)
	at org.eclipse.osgi.container.Module.start(Module.java:449)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:468)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:103)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:529)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:328)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:368)
	at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:36)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:442)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.gemoc.executionframework.extensions.sirius.modelloader.DefaultModelLoader.openNewSiriusSession(DefaultModelLoader.java:237)
	at org.eclipse.gemoc.executionframework.extensions.sirius.modelloader.DefaultModelLoader.loadModel(DefaultModelLoader.java:167)
	at org.eclipse.gemoc.executionframework.extensions.sirius.modelloader.DefaultModelLoader.loadModelForAnimation(DefaultModelLoader.java:128)
	at org.eclipse.gemoc.executionframework.engine.commons.ModelExecutionContext.initializeResourceModel(ModelExecutionContext.java:71)
	at org.eclipse.gemoc.execution.sequential.javaengine.ui.launcher.Launcher.createExecutionEngine(Launcher.java:64)
	at org.eclipse.gemoc.executionframework.engine.ui.launcher.AbstractSequentialGemocLauncher.launch(AbstractSequentialGemocLauncher.java:106)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.lang.ClassNotFoundException: org.snow.xfsmode.xfsmode.adapters.xfsmodemt.XFSMODEAdapter cannot be found by org.snow.xfsmode_1.0.0
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:484)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:564)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:174)
	... 44 more

As far as I am concerned, compared with the debug github from [ https://github.com/gemoc/ICSA2017Tutorial]( https://github.com/gemoc/ICSA2017Tutorial) I lack Melange resource adapter query in debug configuration. Is it necessary?



	
![33](https://user-images.githubusercontent.com/22368519/35434104-db4c0a6c-02c0-11e8-81d1-126fdb6fd379.png)
![22](https://user-images.githubusercontent.com/22368519/35433925-293fae6e-02c0-11e8-8bc9-ef4f3441ab06.png)
![11](https://user-images.githubusercontent.com/22368519/35433930-2ca13b40-02c0-11e8-97d2-20945f22a0c3.png)

**Comment by dvojtise** [comment]
Hi

Currently, when using Gemoc + melange + k3 you can use 2 approaches to build the executable languages : (note that we are working in simplifying/clarifying that)
- one that use 2 languages (one that inherits from the other) (see the wizard templates when creating the project)
![image](https://user-images.githubusercontent.com/661468/35444362-a2db803e-02ae-11e8-9b77-b402132a714b.png) The idea here is to reuse existing models and editors conforming to the non-executable language. It needs melange to do the adaptation when running a model (ie. convert the model that do not contains runtime data into an equivalent model + runtime data) ( https://github.com/gemoc/ICSA2017Tutorial uses this approach). due to the 2 languages, the odesign specification is more complex because it must tackle both the original ecore (in edition mode) and the produced ecore. 

- one that define a single language, however this language is based on an ecore and will produce a second ecore.  
![image](https://user-images.githubusercontent.com/661468/35444652-7f2d5d8c-02af-11e8-8617-00a8acc22dd7.png)
Once produced, the original ecore is supposed to be removed, so the editor must **not** be written on top of the source ecore but on top of the generated ecore. In this mode, melange adaptation is not required when executing the model. (since we directly run a model that has runtime data) 


in your case, it seems that you have your editors (.edit, .editor, .design) based on the source ecore, but you are defining a simple language.  So you need to adapt your editors to the strategy you use.

Didier

**Comment by JoyeGCL** [comment]
Hi dvojtise，
     Thanks again for your kind help. But the problem is still unresolved. 
     Follow your answer above and refer to the steps for the LegacyFSM example you explain here [https://github.com/gemoc/gemoc-studio/issues/59](url), I try again on GemocStudio 3.0.0Build id: 2017-11-24 15:27 . 
     I choose the first approach here you said above. This is my steps, I don't konw if it is still wrong.
1. Create Ecore Modeling Project, complete a ecore and generate all from genmodel, then have edit,editor project
2. Create  and complete a Viewpoint Specification Project 
3. Create a K3 project, indicate the ecore, complete the xtend file
4. New **Simple GEMOC sequential project** named org.sun.fsmode
    4.1 modify the .melange file , add  external
    4.2 right click the .melange file, clean all ,generate all
![1111](https://user-images.githubusercontent.com/22368519/35481890-8e2201bc-0467-11e8-9b86-38af62d0870d.png)


5. New **GEMOC sequential project** named org.sun.xfsmode，indicate the ecore，and the k3 project
   5.1 in the manifest， add a dependency to the org.sun.fsmode
   5.2 right click on the .melange file ,clean all, generate all
    
![2222](https://user-images.githubusercontent.com/22368519/35481892-919311b0-0467-11e8-9bf7-04977db10e8d.png)

  After step5.2, compared with the LegacyFSM example, I find the  src-gen of org.sun.xfsmode is different, lacking the part about Adapter. It confused me a lot. So I right click generate Adapter directly on .melange file, but it sitll looks like this.
![111](https://user-images.githubusercontent.com/22368519/35481809-4c5e2ab8-0466-11e8-8647-787f94450352.png)

Then in Modeling workbench.  I debug my model, but there are still two errors like before.
![666](https://user-images.githubusercontent.com/22368519/35481847-fc8b1392-0466-11e8-8b76-c57c1c743352.png)
![888](https://user-images.githubusercontent.com/22368519/35481848-fecb5ae0-0466-11e8-8290-47baa4ef7884.png)
![777](https://user-images.githubusercontent.com/22368519/35481850-01c77fc6-0467-11e8-8b26-7abbbffa4e53.png)

**Comment by dvojtise** [comment]
you have 2 version of language fsmode : org.sun.fsmode.FSMODE and org.sun.xfsmode.FSMODE

if you mimic fsm, you need to remove the one in Xfsmode.melange and add a dependency to the other project  (use 
```
language XFSMODE inherits org.sun.fsmode.FSMODE
```
